<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'TccAbstractModule\Module'                                               => __DIR__ . '/Module.php',
  'TccAbstractModule\Module\AbstractModule'                                => __DIR__ . '/src/TccAbstractModule/Module/AbstractModule.php',
  'TccAbstractModule\ModuleManager\Feature\AutoloaderProviderDefaultTrait' => __DIR__ . '/src/TccAbstractModule/ModuleManager/Feature/AutoloaderProviderDefaultTrait.php',
  'TccAbstractModule\ModuleManager\Feature\ClassDirTrait'                  => __DIR__ . '/src/TccAbstractModule/ModuleManager/Feature/ClassDirTrait.php',
  'TccAbstractModule\ModuleManager\Feature\ClassNamespaceTrait'            => __DIR__ . '/src/TccAbstractModule/ModuleManager/Feature/ClassNamespaceTrait.php',
  'TccAbstractModule\ModuleManager\Feature\ConfigProviderTrait'            => __DIR__ . '/src/TccAbstractModule/ModuleManager/Feature/ConfigProviderTrait.php',
  'TccAbstractModule\ModuleManager\Feature\ControllerConfigProviderTrait'  => __DIR__ . '/src/TccAbstractModule/ModuleManager/Feature/ControllerConfigProviderTrait.php',
  'TccAbstractModule\ModuleManager\Feature\ServiceConfigProviderTrait'     => __DIR__ . '/src/TccAbstractModule/ModuleManager/Feature/ServiceConfigProviderTrait.php',
  'TccAbstractModule\ModuleManager\Feature\ViewHelperConfigProviderTrait'  => __DIR__ . '/src/TccAbstractModule/ModuleManager/Feature/ViewHelperConfigProviderTrait.php',
);
